service:
  golangci-lint-version: 1.30

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - golint
    - whitespace
    - misspell
    - gosimple
